spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
        hbm2ddl:
          auto: none
  output:
    ansi:
      enabled: always

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true